### ISSUE TITLE
problem with story mode button sprite

### ISSUE THREAD

**Issue by MisterOficerPL** [Pluma-Team/Forever-Engine-Feather#25]
i made an custom menu thats not that complicated right now but theres an problem with the story mode button sprite
its not showing the selected animation tho the other buttons work correctly in other engines it worked normal aswell

any help?

**Comment by BeastlyGhost** [comment]
this may be an animation naming issue, buttons need to be named as `PNG NAME basic` and `PNG NAME white` in order to work, basic being the static animation, white being the selected animation

**Comment by MisterOficerPL** [comment]
yeah i just noticed it skull
