### ISSUE TITLE
chart editor goes black

### ISSUE THREAD

**Issue by legole0** [Pluma-Team/Forever-Engine-Feather#30]
chart editor goes completely black at like 70 seconds in certain songs, on others it makes a little bug where you cant spam D to scroll through the song because it just pauses

i dont know what it causes it but it happens in a new build, i didnt change anything from it

tested it with a friend and it happened for them too

**Comment by legole0** [comment]
forgot to label it as a bug report, but also scrolling up when you're at 0 seconds goes to negative and crashes

**Comment by BeastlyGhost** [comment]
change `"sectionBeats": 4` to `lengthInSteps: 16` in every line that has it on the chart's json file, this is an issue with Psych Engine Charts SPECIFICALLY
