### ISSUE TITLE
[HELP] free play categories

### ISSUE THREAD

**Issue by liri1222335456** [Pluma-Team/Forever-Engine-Feather#31]
like funkin.avi or this shits idk lolololololololololololol soooooooo cool oaoaoaooa :)))))))))))))))))))))))))))))))))))))))))))))))))

**Comment by Ploxycamente2** [comment]
wait for the funkin.avi source to release and copy the codes ::))))_))))))))))))))))))))))))))()))))))))))))))))))))))))))))))))K()))))))))))))))))))))))))))))))

**Comment by liri1222335456** [comment]
how this is a good idea :)))))))))))))))0000000000000000000000000000000000))))KLlli))

**Comment by DEMOLITIONDON96** [comment]
Wait for the release of my source code, for now, just use my recent release of the Psych source of V2, for it's pretty much the same: https://github.com/DEMOLITIONDON96/Funkin.AVI-V2.0-Psych

**Comment by JustJasonLol** [comment]
> like funkin.avi or this shits idk lolololololololololololol soooooooo cool oaoaoaooa :)))))))))))))))))))))))))))))))))))))))))))))))))

### go ahead

[CategoryForeverEdition.zip](https://github.com/Pluma-Team/Forever-Engine-Feather/files/10777797/CategoryForeverEdition.zip)

**Comment by liri1222335456** [comment]
oaooaooaooaoaoaoao okay :)0)00000)0)0)))))))
