### ISSUE TITLE
video playback?

### ISSUE THREAD

**Issue by MisterOficerPL** [Pluma-Team/Forever-Engine-Feather#35]
can you play videos in this engine? (ive had seen hxcodec in project.xml)

**Comment by BeastlyGabi** [comment]
you can but it has never been properly implemented

**Comment by MisterOficerPL** [comment]
damn

**Comment by BeastlyGabi** [comment]
```hx
public function playVideo(onEndSong:Bool = false) {
var videoPlayer:VideoHandler = new VideoHandler();
videoPlayer.playVideo(Paths.getPreloadPath('videos/VIDEO.mp4'));
videoPlayer.onComplete = function() {
     if (!onEndSong)
        startCountdown();
    else
       endSong();
      return;
}
}
```

**Comment by BeastlyGabi** [comment]
should be enough

**Comment by MisterOficerPL** [comment]
im looking to play it on a state like a intro video

**Comment by MisterOficerPL** [comment]
tried to do something myself but:
source/states/IntroState.hx:27: characters 26-38 : Type not found : VideoHandler
source/states/IntroState.hx:28: characters 38-52 : Cannot access private field getPreloadPath
source/states/IntroState.hx:31: characters 32-43 : Class<states.MusicBeatState> has no field switchState
